In [1]:
%matplotlib inline

import sys
import os
import copy
import random
import datetime

import numpy as np
import pickle
import glob
from tqdm import tqdm
from PIL import Image
import torch
import matplotlib.pyplot as plt
import torchvision.transforms as transforms
from torch import optim
from pycocotools.coco import COCO

In [3]:
# classとclassの色の呼び出し
with open('./data/t_class_name.txt', 'rb') as f:
    t_class_name = pickle.load(f)
with open('./data/t_color.txt', 'rb') as f:
    t_color = pickle.load(f)

In [4]:
t_class_name

['person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'dining table',
 'toilet',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush',
 'back']

In [5]:
t_color

[array([156,  43, 238]),
 array([149, 240,  97]),
 array([177, 231, 125]),
 array([252,  84, 204]),
 array([196,  18,   4]),
 array([ 20, 111, 130]),
 array([189, 246, 109]),
 array([ 16,  35, 155]),
 array([132,  19, 115]),
 array([193,  64, 245]),
 array([ 47,  38, 201]),
 array([243,  76, 115]),
 array([250, 231,  29]),
 array([140,   4, 159]),
 array([212, 160,  32]),
 array([ 31, 252, 115]),
 array([143, 250, 186]),
 array([ 52, 161, 181]),
 array([  6, 160,  85]),
 array([ 53, 161,  45]),
 array([220, 233,   6]),
 array([ 93, 197,  68]),
 array([ 15,  59, 106]),
 array([ 34,  64, 224]),
 array([  3, 123, 237]),
 array([154, 125,  76]),
 array([ 92,  20, 216]),
 array([ 28, 124, 212]),
 array([ 15, 132, 119]),
 array([195,  34,  81]),
 array([ 43, 108, 199]),
 array([ 34, 185, 227]),
 array([ 64, 114, 211]),
 array([237, 183,  57]),
 array([250,  48, 204]),
 array([  1, 223, 130]),
 array([ 14, 187, 119]),
 array([118, 195, 123]),
 array([213,  45,  92]),
 array([ 42,  86, 241]),


In [6]:
len(t_class_name) == len(t_color)

True

In [7]:
doc_class_name = ['Background', 'TextRegion', 'ImageRegion', 'TableRegion', 'MathsRegion', 'SeparatorRegion', 'OtherRegion']

In [9]:
doc_cls_color = t_color[0:7]
doc_cls_color

[array([156,  43, 238]),
 array([149, 240,  97]),
 array([177, 231, 125]),
 array([252,  84, 204]),
 array([196,  18,   4]),
 array([ 20, 111, 130]),
 array([189, 246, 109])]

In [10]:
len(doc_class_name) == len(doc_cls_color)

True

In [12]:
# Open a file and use dump()
with open('prima_cls.pkl', 'wb') as file:
    pickle.dump(doc_class_name, file)

In [13]:
# Open a file and use dump()
with open('gen_cls_color.pkl', 'wb') as file:
    pickle.dump(doc_cls_color, file)